server:
  port: 8001
spring:
  application:
    name: order
  config:
    import: optional:configserver:http://127.0.0.1:8888
  profiles:
    active: dev
  cloud:
    config:
      label: master
      profile: ${spring.profiles.active}