server:
  port: 8000
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://127.0.0.1:8888
  profiles:
    active: home
  cloud:
    config:
      label: master
      profile: ${spring.profiles.active}