spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.0.202:1521/kfdb.zt
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      username: gsywjz
      password: zenithinfo
      minimum-idle: 10
      maximum-pool-size: 25
      idle-timeout: 300000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: select 1 from dual
  activiti:
    history-level: full
    db-history-used: true