server:
  port: 8006
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8005/oauth/check_token
    client:
      client-id: client
      client-secret: client
      access-token-uri: http://localhost:8005/oauth/token
      authorized-grant-types:
        - password
        - authorization_code
        - client_credentials
        - implicit
        - refresh_token
      scope: all
      auto-approve-scopes: true